export * from '../globalActionNames'

export const PomodoroStarted = 'PomodoroStarted'
export const PomodoroCompleted = 'PomodoroCompleted'
export const PomodoroSquashed = 'PomodoroSquashed'
export const PomodoroVoided = 'PomodoroVoided'
export const LoggedIn = 'LoggedIn'
export const ResumeTimer = 'ResumeTimer'
export const UpdateTimer = 'UpdateTimer'
export const NeedLogin = 'NeedLogin'
export const StartRequested = 'StartRequested'
export const StartCanceled = 'StartCanceled'
export const Init = 'Init'
export const TimersLoaded = 'TimersLoaded'
export const UsersLoaded = 'UsersLoaded'
export const TagsLoaded = 'TagsLoaded'
export const SelectedUsersChanged = 'SelectedUsersChanged'

